### ISSUE TITLE
Proposed change all licences to EPL 1.0 or update existing ALv2

### ISSUE THREAD

**Issue by AndyGee** [eclipse/microprofile-conference#131]
Proposed change to https://www.eclipse.org/legal/epl-v10.html - See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/microprofile/UvPWRMOtcfk/U5QyauJdCAAJ

**Comment by karianna** [comment]
I think the community is still discussing whether to do this.

**Comment by kwsutter** [comment]
We are using the Apache v2 license with all of the MicroProfile material, even as part of the Eclipse project.

**Comment by kwsutter** [comment]
Closed issue.  We are using Apache v2 License.
