### ISSUE TITLE
Remove or replace JavaOne2016.json

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-conference#154]
Input from a recent review...

We note the Microprofile conference master (microservice-speaker resources)
specifically contain information that looks to originate from Oracle's
JavaOne2016 Conference.  At least the name of the file implies this association...

As this appears to contain Oracle Assets, we need help with understanding
where the content was taken from in order that we can investigate
any associated Terms of Use, etc.  Or was this content contributed by Oracle to
the project?  Doubt it...  It was just used for testing purposes...

microprofile-conference-master/microservice-speaker/src/main/resources/JavaOne2016.json

Looking at the content of this file, it seems to contain some of the speakers from JavaOne.  How did we retrieve this information?  Are we using it with Oracle's permission?  If this is just used for testing, maybe we could rename this and cull it down to just our key participants?  We need to do something with this file...

**Comment by kwsutter** [comment]
Assigning this to Andy since it looks like he committed this in the first place.  Thanks.

**Comment by mikecroft** [comment]
It would be nice if we could use a service like http://www.generatedata.com/ to replace the data with some made up stuff. It looks like that site in particular isn't any kind of legal entity, so that might not fit with Eclipse's IP guidance either!

**Comment by kwsutter** [comment]
A bit more information on this request...  It looks like we have 86 entries with the following json format:

{
  "id" : "00",
  "nameFirst" : "Kevin",
  "nameLast" : "Sutter",
  "organization" : "IBM",
  "biography" : "Java EE and MicroProfile Architect",
  "picture" : "assets/images/unknown.jpg",
  "twitterHandle" : null,
  "links" : { }
}

The "links" are currently empty for all entries.  Most "twitterHandles" are null, and most "pictures" are unknown.jpg.

We either need some "generated data" like Mike suggested, or we need some data volunteered from another conference.

**Comment by kwsutter** [comment]
Used generatedata.com to generate random data for JavaOne2016.json and for speakers.json.  But, I also found schedule.json which is proving more difficult.  I'm requesting assistance from Heiko...

**Comment by heiko-braun** [comment]
@kwsutter https://github.com/eclipse/microprofile-conference/pull/156 replaces the data in demo-bootstrap. AFAIKT this is used in the majority of services to bootstrap their local data stores. It might replace/supersede your work at https://github.com/eclipse/microprofile-conference/pull/155

**Comment by kwsutter** [comment]
Resolved via PR #156 and PR #157.  Thanks, @heiko-braun!
