### ISSUE TITLE
Demonstrate Fault Tolerance feature

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-conference#164]
Conference app needs to demonstrate Fault Tolerance feature

**Comment by Emily-Jiang** [comment]
Andy Guibert is working on updating vote service to demonstrate FT on WebSphere Liberty.

**Comment by carlosdlr** [comment]
Hello emily,

my name is carlos and i'm new on the community if you want I can help on this

Thank you

**Comment by Emily-Jiang** [comment]
Thanks @carlosdlr ! This issue was done by #173 . However, if you have better idea to demonstrate more FT in the conference app, it will be great.

**Comment by mikecroft** [comment]
Closing this issue since, as @Emily-Jiang says, it is resolved by #173
