### ISSUE TITLE
Need to update to MicroProfile 1.2 and create a 1.1 branch

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-conference#175]
We need to update to the 1.2 MicroProfile release and create a 1.1 branch.

**Comment by starksm64** [comment]
An MP-1.1 branch has been created at 53dee0aac31390b5ca7da04b4b2f5f31000cf8a9

**Comment by aguibert** [comment]
Delivered this change under https://github.com/eclipse/microprofile-conference/pull/179
